# Generated by Django 3.2 on 2022-11-01 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentstudentlearning',
            name='observer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.customuser', verbose_name='Наблюдатель'),
            preserve_default=False,
        ),
    ]
